[package]
name = "generated_project"
version = "0.15.5"
edition = "2021"
default-run = "run"
[workspace]

exclude = [
    ".pax",
]

[dependencies]
pax-engine = { version = "0.15.5" , path = ".pax/pkg/pax-engine" }
pax-std = { version = "0.15.5" , path = ".pax/pkg/pax-std" }
rand = {version = "0.8.5"}
getrandom = { version = "0.2.14", features = ["js"] }

[[bin]]
name = "run"
path = "bin/run.rs"
