[package]
name = "pax-gpu"
version = "0.39.0"
edition = "2021"
authors = ["Samuel Selleck <sellecksamuel@gmail.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://pax.dev/"
repository = "https://www.github.com/paxproject/pax"
description = "WGPU rendering library for the pax framework"

[dependencies]
pax-runtime-api = {path = "../pax-runtime-api", version="0.39.0"}
log = "0.4.20"
bytemuck = { version = "1.14", features = ["derive"] }
anyhow = "1.0"
lyon = "1.0.1"
winit = "0.27.5"
web-sys = { version = "0.3.64", features = ["HtmlCanvasElement"] }
js-sys = "0.3.64"
wasm-bindgen-futures = "0.4.38"

[features]
default = []

[dev-dependencies]
naga = { version = "28.0.0", features = ["wgsl-in"] }

[target.'cfg(target_os = "macos")'.dev-dependencies]
objc2 = "0.6.4"
pollster = "0.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies.wgpu]
version = "28.0.0"
default-features = false
features = [
    "std",
    "wgsl",
    "webgpu",
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.wgpu]
version = "28.0.0"
default-features = false
features = [
    "std",
    "parking_lot",
    "dx12",
    "metal",
    "gles",
    "vulkan",
    "wgsl",
]
