[package]
name = "transition-grid"
version = "0.38.3"
edition = "2021"
default-run = "run"

[dependencies]
rand = { version = "0.8.5" }
getrandom = { version = "0.2.15", features = ["js"] }
pax-kit = { version = "0.38.3", path="../../../pax-kit" }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "run"
path = "bin/run.rs"
