[workspace]

members = [
    "pax-lang",
    "pax-core",
    "pax-chassis-web",
    "pax-chassis-macos",
    "pax-macro",
    "pax-message",
    "pax-compiler",

    "pax-runtime-api",
    "pax-cli",
    "pax-std",
    "pax-std/pax-std-primitives",

    # Note: if we want to add `pax-example` to the workspace, we'll need to
    # pursue a work-around like: https://github.com/rust-lang/cargo/issues/5418#issuecomment-384926507
    # Specifically: patch the generated Cargo.toml for `.pax/chassis/**/Cargo.toml` to include
    # the empty workspace def
]

exclude = [
    "pax-cartridge",
    "pax-example",
    "pax-properties-coproduct",
    "pax-example/.pax/chassis/MacOS",
    "pax-example/.pax/chassis/Web",
    "pax-chassis-macos/pax-dev-harness-macos",
]

[profile.release]
lto = true
opt-level = 'z'


