[workspace]

members = [
    "pax-lang",
    "pax-core",
    "pax-macro",
    "pax-message",
    "pax-compiler",
    "pax-runtime-api",
    "pax-cli",
    "pax-std",
    "pax-std/pax-std-primitives",
]

exclude = [
    "pax-cartridge",
    "pax-compiler/new-project-template",
    "pax-example",
    "pax-properties-coproduct",
    "pax-chassis-macos/pax-dev-harness-macos",
    "pax-create-sandbox",
]

[profile.release]
lto = true
opt-level = 'z'


