[package]
name = "pax-monorepo"
version = "0.10.10"
authors = ["Zack Brown <zack@pax.dev>", "Warfa Jibril <warfa@pax.dev>"]
edition = "2021"

[workspace]
members = [
    "pax-chassis-web",
    "pax-chassis-macos",
    "pax-chassis-ios",
    "pax-chassis-common",
    "pax-engine",
    "pax-runtime",
    "pax-macro",
    "pax-message",
    "pax-compiler",
    "pax-cli",
    "pax-std",
    "pax-std/pax-std-primitives",
    "pax-manifest",
]

exclude = [
    "pax-cartridge",
    "pax-compiler/new-project-template",
    "pax-create-sandbox",
    "pax-language-server",
    "examples",
    "www.pax.dev/src/website",
]

[profile.release]
lto = true
opt-level = 'z'


