[package]
name = "dynamic-linking-lab"
version = "0.38.3"
edition = "2021"
default-run = "run"

[dependencies]
pax-kit = { version = "0.38.3", path = "../../../pax-kit" }

[lib]
crate-type = ["cdylib", "rlib"]
name = "paxcartridge"

[[bin]]
name = "run"
path = "bin/run.rs"

[profile.dev]
opt-level = 0
debug = false

[profile.dev.package."*"]
opt-level = 2
debug = false
