#!/bin/bash

### Helper script for pax libdev, allowing pax-cli-like ergonomics inside the pax-example directory
###
### For example, from @/pax root:
### `cd pax-example && ./pax run --target=macos`
### `cd pax-example && ./pax parse`
### `cd pax-example && ./pax libdev build-chassis`
set -e

# Set the PAX_WORKSPACE_ROOT environment variable
export PAX_WORKSPACE_ROOT=$(realpath "../../../../..")

current_dir=$(pwd)
pushd ../../../../../pax-cli
cargo build
../target/debug/pax-cli "$@" --path="$current_dir" --libdev
popd
