[package]
name = "particles"
version = "0.32.0"
edition = "2021"
default-run = "run"

[dependencies]
rand = { version = "0.8.5" }
getrandom = { version = "0.2.15", features = ["js"] }
pax-kit = { version = "0.32.0", path="../../../pax-kit", features = ["designer"] }

[lib]
crate-type = ["cdylib", "rlib"]
name = "paxcartridge"

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
designer = ["pax-kit/designer"]
parser = ["pax-kit/parser"]
web = ["pax-kit/web"]
macos = ["pax-kit/macos"]
ios = ["pax-kit/ios"]

[profile.dev]
opt-level = 2
debug = false