//! Component names and explanations. Coordinates live in layout.rs.

pub struct PartSpec {
    pub id: &'static str,
    pub title: &'static str,
    pub interface: &'static str,
    pub explanation: &'static str,
    pub source: &'static str,
}

macro_rules! part {
    ($id:literal, $title:literal, $interface:literal, $explanation:literal, $source:literal) => {
        PartSpec {
            id: $id,
            title: $title,
            interface: $interface,
            explanation: $explanation,
            source: $source,
        }
    };
}

pub const PARTS: &[PartSpec] = &[
    part!("source", "Pax + Rust", "templates · logic · assets", "Pax describes structure, bindings and events. Rust owns application state, handlers and side effects. Asset references accompany the program.", "pax-docs/book/src/getting-started.md"),
    part!("construct.analyze", "Parser", "grammar · types · PAXEL", "Analyzes templates and Rust component metadata into definitions, expressions, settings, timelines and handler bindings. Standard-library components enter this same path.", "pax-compiler/src/static_analysis.rs"),
    part!("construct.connect", "Cartridge generator", "descriptors · program data", "Connects declarative definitions to compiled Rust types and handlers. Debug uses rich manifest data; release embeds program data as Rust constructors. This diagram does not claim that normal startup decodes binary ProgramIR.", "pax-compiler/src/cartridge_generation/mod.rs"),
    part!("cartridge", "Cartridge", "application / runtime interface", "The generated application-specific connection supplies startup definitions, descriptors and Rust behavior. It is compiled for the target, not one interchangeable binary for every platform.", "pax-compiler/templates/cartridge_generation/cartridge.tera"),
    part!("construct.instantiate", "Definition traverser", "DefinitionToInstanceTraverser", "Reads template definitions and the descriptor registry to construct reusable InstanceNode behavior and property initialization plans. The chassis requests the main component at startup.", "pax-runtime/src/cartridge.rs"),
    part!("instance.behavior", "InstanceNode", "reusable · type-aware", "Connects a template definition to type-aware behavior. An InstanceNode can support multiple ExpandedNode instances, for example through a repeated template.", "pax-runtime/src/rendering.rs"),
    part!("construct.expand", "Instance expander", "scope · bindings · lifecycle", "Creates concrete instances, connects their properties and effects, and registers lifecycle and lookup state. Control flow reuses expansion when branches, repetitions and routes change.", "pax-runtime/src/engine/expanded_node.rs"),
    part!("scene", "Scene graph", "ExpandedNode instances", "The live expanded component tree owns concrete state and relationships. Template ownership, render ancestry, received children and retained exits are distinct relationships. It is coupled to the Dirty DAG, not interchangeable with it.", "pax-runtime/src/engine/expanded_node.rs"),
    part!("operate.drive", "Event handlers", "dispatcher · NodeContext", "Dispatch resolves event bindings and calls Rust handlers with typed event data and component state. Property writes from handlers enter the same Dirty DAG as clocks, lifecycle callbacks and external results.", "pax-runtime/src/engine/mod.rs"),
    part!("operate.react.properties", "Properties", "values · dependency links", "Properties hold source or cached values and dependency links. They belong to instance state while participating in the Dirty DAG; the diagram does not imply a copied application-state store.", "pax-runtime-api/src/properties/mod.rs"),
    part!("operate.react.evaluate", "PAXEL evaluator", "expressions · bindings", "A read demands current values from dirty dependencies. Expressions evaluate in instance scope; eligible direct bindings use typed fast paths. Rust handlers remain compiled application logic.", "pax-language/src/interpreter/mod.rs"),
    part!("operate.react.dirty", "Dirty propagation", "dependents · cutoffs", "A Property write invalidates downstream computations and queues affected effects. Configured cutoff computations can stop propagation when the accepted value remains unchanged.", "pax-runtime-api/src/properties/graph_operations.rs"),
    part!("operate.react.effects", "Effect queue", "registered consumers", "The runtime drains pending consumers around lifecycle, clock and event boundaries. Consumers turn invalidation into structural changes, native patches and render work. Property writes are not whole-scene transactions.", "pax-runtime-api/src/properties/properties_table.rs"),
    part!("operate.structure", "Control flow resolution", "if · for · routes · slots", "Conditions, keyed repetition, routing and slot projection select participating instances. Instance expansion and balanced lifetime management maintain the scene graph and its property connections; exiting instances may remain mounted for transitions.", "pax-runtime/src/{conditional,repeat,router,slot}.rs"),
    part!("operate.geometry", "Layout", "bounds · transforms", "Units, anchors, parent geometry and container placement produce reactive bounds and transforms. Native measurements feed sizing; viewport and scroll state contribute presentation coordinates.", "pax-runtime/src/layout.rs"),
    part!("operate.geometry.index", "Scene geometry", "prepared spatial index", "Prepared records serve replay and composition queries. The runtime scene index selects instances intersecting replay regions. Detached mask sources reuse prepared geometry without entering visible spatial indexes.", "pax-runtime/src/scene_geometry.rs"),
    part!("operate.opacity", "Opacity scopes", "authored ancestry", "Preserves authored boundaries for canvas group composition and effective opacity for native presentation and coverage. Canvas children compose before their boundary opacity is applied; separate native surfaces still fade independently.", "pax-runtime/src/engine/expanded_node.rs"),
    part!("operate.project", "Primitive hooks", "update · render · coverage", "Consume resolved state and geometry. Primitive implementations invalidate canvas work, emit native patches and supply coverage or render hooks. Coverage used for native occlusion can be conservative.", "pax-runtime/src/rendering.rs"),
    part!("present.plan.layers", "Layer partitioner", "order · surface ownership", "Traverses presentation order and assigns logical layers and Scroller-owned islands. Source order, render ancestry and native surfaces constrain composition.", "pax-runtime/src/engine/occlusion.rs"),
    part!("present.plan.coverage", "Clip resolver", "Frame · geometric Mask", "Resolves transformed coverage and geometric clips. Frame contributes rectangular or rounded bounds; a geometric Mask uses source geometry. Native coverage remains an approximation rather than final-pixel sampling.", "pax-runtime/src/engine/occlusion.rs"),
    part!("present.plan.tiles", "Tile planner", "LayerCanvasPlan", "Selects a bounded surface window from layer ownership, viewport, extents and chassis limits. Plans include reusable slots, origins and visible/prewarm priorities. Tiling limits graphics surfaces; it does not virtualize component instances.", "pax-runtime/src/engine/layer_tiling.rs"),
    part!("present.plan.occlusion", "Native occlusion", "coverage · punch-through", "Transforms drawn coverage above native elements into native-local mask patches. Geometry and opacity estimates preserve mixed ordering, with documented limitations for translucent overlaps.", "pax-runtime/src/engine/occlusion.rs"),
    part!("present.work.replay", "Replay planner", "surface regions · batches", "Surface layout changes determine replay regions and priority batches. SurfaceReplayCoordinator owns surface indices and pending regions. SceneGeometry selects nodes. This explicit split corrects the earlier broad label; it is not by itself evidence of code debt.", "pax-runtime/src/engine/layer_surface.rs"),
    part!("present.work.dirty", "Dirty render planner", "traversal · fallback", "Reconciles ordinary invalidation, targeted replay and removals. Selects a filtered scene traversal or a broader fallback. Architectural review should inspect this contract with surface batching rather than assume one replay owner does everything.", "pax-runtime/src/engine/mod.rs"),
    part!("present.lights", "Light collector", "LightFrame · layer lights", "Collects transformed LightSource and AmbientLight values. LightFrame ancestry controls per-node direct-light eligibility. Up to eight direct lights serve a layer; native elements and bitmap images are not lit vector materials. Piet paints unlit.", "pax-runtime/src/properties.rs"),
    part!("present.work.cull", "Surface culler", "draw / tile intersection", "Uses prepared coverage to route a node's draw only to intersecting physical surfaces, with conservative fallbacks. This decision is distinct from tile existence, replay priority and dirty traversal.", "pax-runtime/src/engine/pax_gpu_render_context.rs"),
    part!("present.patch", "Native patch generator", "NativeMessage", "Primitive updates and compositor results produce native create/update/delete, style, transform and mask messages. Native text and controls do not pass through the vector drawing pipeline.", "pax-message/src/lib.rs"),
    part!("present.draw.adapter", "RenderContext adapter", "logical layer / surface", "Routes primitive render hooks and clip state to physical surface renderers, translating into surface coordinates. Web chooses WGPU or the Piet alternative according to configuration and availability.", "pax-runtime/src/engine/pax_gpu_render_context.rs"),
    part!("present.draw.retained", "Retained drawing records", "geometry · resource caches", "Retains vector and image records keyed by node, order, bounds, transform and clips. Shared caches reuse geometry and GPU data. Record reuse is separate from retaining composed subtree pixels.", "pax-gpu/src/render_context.rs"),
    part!("present.draw.vector", "Vector pipeline", "paths · fill / stroke layers", "Prepares smoothed geometry and reveal ranges, tessellates and reuses GPU buffers. Ordered fill/stroke layers supply paint. Their combined appearance participates in element and group opacity.", "pax-gpu/src/render_context.rs"),
    part!("present.draw.materials", "Paints + materials", "gradients · light response", "Paints supply color and alpha. Material parameters provide ambient, diffuse, specular, roughness and emissive response in the vector shader. A GPU image texture is not automatically an authored material texture map.", "pax-gpu/src/render_backend/geometry.wgsl"),
    part!("present.draw.textures", "Textures", "images · GPU resources", "Versioned image resources feed the image pipeline. Mask coverage, stencil and multisample attachments have separate purposes. Changed shared images invalidate dependent retained content.", "pax-gpu/src/render_backend/texture.rs"),
    part!("present.draw.stencil", "Stencil renderer", "nested geometric clips", "Synchronizes clip stacks and caches tessellated clip geometry. Stencil tests restrict vector and image drawing independently of painted alpha masks.", "pax-gpu/src/render_backend/stencil.rs"),
    part!("present.draw.capture", "Subtree rasterizer", "shared retained surfaces", "Composes ordered retained draws into reusable offscreen surfaces. Content signatures control pixel reuse and retirement. CaptureKey::Opacity and CaptureKey::Alpha share this machinery. It does not flatten arbitrary mixed native surfaces.", "pax-gpu/src/render_backend/capture.rs"),
    part!("present.draw.alpha", "Alpha mask", "source capture · coverage", "A live vector-producing source subtree renders only into its capture. Extracted alpha is feathered and combined with enclosing masks, then sampled by content draws. Source clips and group opacity are preserved. Images, native leaves, source-side Scrollers and Piet alpha masks are unsupported.", "pax-gpu/src/render_context/source_capture.rs"),
    part!("present.draw.capture.opacity", "Opacity compositor", "boundary opacity · cached pixels", "Composes children first, then samples the retained result with boundary opacity. Opacity-only changes can reuse composed pixels. Browser Piet uses temporary canvases without retaining those pixels between dirty frames.", "pax-gpu/src/render_context/opacity.rs"),
    part!("present.draw.submit", "GPU backend", "device · queue · pipelines", "Device, queue, pipelines and per-surface backends encode ordered work, resolve multisampling and present the graphics surfaces hosted by the chassis.", "pax-gpu/src/render_backend/mod.rs"),
    part!("feedback.clock", "Frame scheduler", "ticks · clocks · playheads", "Host frame callbacks drive tick/render and clock advancement. The engine settles effects and limits canvas work through dirty tracking; a live frame callback does not imply every surface redraws.", "pax-chassis-web/src/lib.rs"),
    part!("feedback.input", "Input adapter", "NativeInterrupt", "Translates native input and control notifications, preserving target identity or using resolved geometry for hit testing. Dispatch invokes the appropriate handler and closes the property-update loop.", "pax-message/src/lib.rs"),
    part!("chassis.bridge", "Native bridge", "Wasm / DOM · C ABI / Swift", "Web crosses Rust/Wasm to TypeScript/DOM. Apple targets cross the shared Rust C ABI to Swift/native views. Both exchange native patches, input and host measurements.", "pax-chassis-common/src/core_graphics_c_bridge.rs"),
    part!("chassis.native", "Native elements", "text · controls · Scrollers", "Platform-native elements retain identity and provide text, controls, scrolling and accessibility behavior. Their measured sizes and scroll offsets return to the runtime. Native content remains separately composed from GPU subtree captures.", "pax-compiler/files/interfaces/web/src/classes/native-element-pool.ts"),
    part!("chassis.masks", "Native masks", "SVG / native raster masks", "Realizes native-local geometry and occlusion masks. Web uses SVG effect machinery; Apple uses cached raster mask images and native clip layers. These mask resources are not captures of native content.", "pax-compiler/files/swift/pax-swift-common/Sources/Rendering/Rendering.swift"),
    part!("chassis.surfaces", "Surface manager", "canvas · GPU surfaces", "Creates, reuses, resizes and places surfaces according to LayerCanvasPlan. Returns handles, scale and readiness. Layout retargets can invalidate retained records and require replay.", "pax-compiler/files/interfaces/web/src/classes/render-layer-context.ts"),
    part!("present.compose", "Host compositor", "graphics + native elements", "The browser or native platform presents graphics surfaces with live elements in shared scene coordinates and order. Mixed-surface blending is subject to the documented native coverage limits.", "pax-docs/book/src/compositing-effects.md"),
    part!("feedback.resource", "Resource loader", "images · fonts · readiness", "Resolves resource references and returns decoded pixels or native readiness to their consumer. Application-side asynchronous results may also update Properties.", "pax-runtime-api/src/lib.rs"),
];
