//! Event payloads and cancellation wrappers passed to Pax event handlers.

use super::*;

// Unified events

/// Event wrapper passed to Pax event handlers.
///
/// `Event<T>` carries the typed event payload and shared cancellation state,
/// allowing handlers to call `prevent_default` where the active chassis supports it.
#[derive(Clone)]
pub struct Event<T> {
    /// The event-specific payload, for example `Click` or `KeyDown`.
    pub args: T,
    // Shared cancellation state, so cloned event wrappers preserve `prevent_default`.
    cancelled: Rc<Cell<bool>>,
}

impl<T: Clone + 'static> ImplToFromPaxAny for Event<T> {}

impl<T> Event<T> {
    /// Constructs an event wrapper around a raw payload.
    pub fn new(args: T) -> Self {
        Self {
            args,
            cancelled: Default::default(),
        }
    }

    /// Cancels the platform default for this event, when the chassis supports cancellation.
    pub fn prevent_default(&self) {
        self.cancelled.set(true);
    }

    // Whether `prevent_default` has been called.
    pub fn cancelled(&self) -> bool {
        self.cancelled.get()
    }
}

impl<T> Deref for Event<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.args
    }
}

/// A ClickOrTap describes either a "click" (mousedown followed by mouseup), OR a
/// "tap" with one finger (singular fingerdown event).
/// ClickOrTap is useful when you want the same behavior for both to be contained
/// in one place.
#[derive(Clone)]
pub struct ClickOrTap {
    /// The x-coordinate of the click-or-tap in the receiving node's local coordinate space.
    pub x: f64,
    /// The y-coordinate of the click-or-tap in the receiving node's local coordinate space.
    pub y: f64,
}

/// Scroll is the shared delta-based path for wheel scrolling, touch swipe gestures, and
/// read-only native scroller position changes.
/// Use `Wheel` or `TouchMove` when you need platform-specific details instead of the normalized
/// delta stream.
#[derive(Clone)]
pub struct Scroll {
    /// Horizontal scroll delta.
    pub delta_x: f64,
    /// Vertical scroll delta.
    pub delta_y: f64,
}

// Touch Events

/// Represents a single touch event.
#[derive(Clone)]
pub struct Touch {
    /// The x-coordinate of this touch point.
    pub x: f64,
    /// The y-coordinate of this touch point.
    pub y: f64,
    /// Stable identifier for this touch across a touch sequence.
    pub identifier: i64,
    /// Horizontal delta since the previous touch update.
    pub delta_x: f64,
    /// Vertical delta since the previous touch update.
    pub delta_y: f64,
}

impl From<&TouchMessage> for Touch {
    fn from(value: &TouchMessage) -> Self {
        Touch {
            x: value.x,
            y: value.y,
            identifier: value.identifier,
            delta_x: value.delta_x,
            delta_y: value.delta_y,
        }
    }
}

/// A TouchStart occurs when the user touches an element.
/// The contained `touches` represent a list of touch points.
#[derive(Clone)]
pub struct TouchStart {
    /// Active touch points at the start of this touch sequence.
    pub touches: Vec<Touch>,
}

/// A TouchMove occurs when the user moves while touching an element.
/// The contained `touches` represent a list of touch points.
#[derive(Clone)]
pub struct TouchMove {
    /// Active touch points after this touch movement.
    pub touches: Vec<Touch>,
}

/// A TouchEnd occurs when the user stops touching an element.
/// The contained `touches` represent a list of touch points.
#[derive(Clone)]
pub struct TouchEnd {
    /// Touch points that ended.
    pub touches: Vec<Touch>,
}

// Keyboard Events

/// Common properties in keyboard events.
#[derive(Clone)]
pub struct KeyboardEventArgs {
    /// Platform-normalized key string.
    pub key: String,
    /// Modifier keys active during the event.
    pub modifiers: Vec<ModifierKey>,
    /// Whether this event was generated by key-repeat.
    pub is_repeat: bool,
}

/// User is pressing a key.
#[derive(Clone)]
pub struct KeyDown {
    /// Common keyboard event data.
    pub keyboard: KeyboardEventArgs,
}

/// A native text selection is beginning.
#[derive(Clone)]
pub struct SelectStart {}

/// User has released a key.
#[derive(Clone)]
pub struct KeyUp {
    /// Common keyboard event data.
    pub keyboard: KeyboardEventArgs,
}

/// User presses a key that displays a character (alphanumeric or symbol).
#[derive(Clone)]
pub struct KeyPress {
    /// Common keyboard event data.
    pub keyboard: KeyboardEventArgs,
}

/// Window or component focused.
#[derive(Clone)]
pub struct Focus {}

// Mouse Events

/// Common properties in mouse events.
#[derive(Clone)]
pub struct MouseEventArgs {
    /// The x-coordinate of the mouse event in the receiving node's local coordinate space.
    pub x: f64,
    /// The y-coordinate of the mouse event in the receiving node's local coordinate space.
    pub y: f64,
    /// Mouse button associated with the event.
    pub button: MouseButton,
    /// Modifier keys active during the event.
    pub modifiers: Vec<ModifierKey>,
}

/// The variants of mouse buttons available on mouse-supporting platforms.
#[derive(Clone, PartialEq)]
pub enum MouseButton {
    /// Primary mouse button.
    Left,
    /// Secondary mouse button.
    Right,
    /// Middle mouse button.
    Middle,
    /// Button not identified by the chassis.
    Unknown,
}

impl From<MouseButtonMessage> for MouseButton {
    fn from(value: MouseButtonMessage) -> Self {
        match value {
            MouseButtonMessage::Left => MouseButton::Left,
            MouseButtonMessage::Right => MouseButton::Right,
            MouseButtonMessage::Middle => MouseButton::Middle,
            MouseButtonMessage::Unknown => MouseButton::Unknown,
        }
    }
}

/// The variants of modifier keys available on keyboard-supporting platforms.
#[derive(Clone)]
pub enum ModifierKey {
    /// Shift key.
    Shift,
    /// Control key.
    Control,
    /// Alt or Option key.
    Alt,
    /// Command, Meta, or Windows key.
    Command,
}

impl From<&ModifierKeyMessage> for ModifierKey {
    fn from(value: &ModifierKeyMessage) -> Self {
        match value {
            ModifierKeyMessage::Shift => ModifierKey::Shift,
            ModifierKeyMessage::Control => ModifierKey::Control,
            ModifierKeyMessage::Alt => ModifierKey::Alt,
            ModifierKeyMessage::Command => ModifierKey::Command,
        }
    }
}

/// User clicks a mouse button over an element.
#[derive(Clone)]
pub struct Click {
    /// Common mouse event data.
    pub mouse: MouseEventArgs,
}

/// User drops a file-like payload over an element.
#[derive(Clone)]
pub struct Drop {
    /// The x-coordinate of the drop in the receiving node's local coordinate space.
    pub x: f64,
    /// The y-coordinate of the drop in the receiving node's local coordinate space.
    pub y: f64,
    /// File or payload name supplied by the platform.
    pub name: String,
    /// MIME type supplied by the platform.
    pub mime_type: String,
    /// Raw dropped payload bytes.
    pub data: Vec<u8>,
}

/// User double-clicks a mouse button over an element.
#[derive(Clone)]
pub struct DoubleClick {
    /// Common mouse event data.
    pub mouse: MouseEventArgs,
}

/// User moves the mouse while it is over an element.
#[derive(Clone)]
pub struct MouseMove {
    /// Common mouse event data.
    pub mouse: MouseEventArgs,
}

/// User scrolls the mouse wheel over an element.
#[derive(Clone)]
pub struct Wheel {
    /// The x-coordinate of the wheel event in the receiving node's local coordinate space.
    pub x: f64,
    /// The y-coordinate of the wheel event in the receiving node's local coordinate space.
    pub y: f64,
    /// Horizontal wheel delta.
    pub delta_x: f64,
    /// Vertical wheel delta.
    pub delta_y: f64,
    /// Modifier keys active during the event.
    pub modifiers: Vec<ModifierKey>,
}

/// User checks or unchecks a checkbox.
#[derive(Clone)]
pub struct CheckboxChange {
    /// The new checked state.
    pub checked: bool,
}

/// User types into a text input field.
#[derive(Clone)]
pub struct TextInput {
    /// Text committed by the input event.
    pub text: String,
}

/// User changes the text in a text input field.
#[derive(Clone)]
pub struct TextboxChange {
    /// Current text after the change.
    pub text: String,
}

/// User types into a text input field and presses enter, or the field loses focus after being changed.
#[derive(Clone)]
pub struct TextboxInput {
    /// Text committed by the input event.
    pub text: String,
}

/// User clicks a button.
#[derive(Clone)]
pub struct ButtonClick {}

/// User presses a mouse button over an element.
#[derive(Clone)]
pub struct MouseDown {
    /// Common mouse event data.
    pub mouse: MouseEventArgs,
}

/// User releases a mouse button over an element.
#[derive(Clone)]
pub struct MouseUp {
    /// Common mouse event data.
    pub mouse: MouseEventArgs,
}

/// User moves the mouse onto an element.
#[derive(Clone)]
pub struct MouseOver {}

/// User moves the mouse away from an element.
#[derive(Clone)]
pub struct MouseOut {}

/// User right-clicks an element to open the context menu.
#[derive(Clone)]
pub struct ContextMenu {
    /// Common mouse event data.
    pub mouse: MouseEventArgs,
}
