[package]
name = "perf-testbed"
version = "0.38.2"
edition = "2021"
default-run = "run"

[dependencies]
pax-kit = { version = "0.38.2", path = "../../../pax-kit" }
rand = { version = "0.8.5" }
getrandom = { version = "0.2.15", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
parser = ["pax-kit/parser"]
web = ["pax-kit/web"]
macos = ["pax-kit/macos"]
ios = ["pax-kit/ios"]

[profile.parser]
inherits = "dev"
opt-level = 0

[profile.parser.package."*"]
inherits = "dev"
opt-level = 0

[profile.dev]
opt-level = 3
debug = false

[profile.dev.package."*"]
opt-level = 3
debug = false
