[package]
name = "pax-std-primitives"
version = "0.6.6"
authors = ["Zack Brown <zack@pax.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://pax.dev/"
repository = "https://www.github.com/pax-lang/pax"
description = "Primitives crate for Pax's standard library"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pax-lang = {path = "../../pax-lang", version="0.6.6"}
pax-core = {path = "../../pax-core", version="0.6.6"}
pax-std = {path = "../", version="0.6.6"}
pax-runtime-api = {path = "../../pax-runtime-api", version="0.6.6"}
pax-message = {path = "../../pax-message", version="0.6.6" }
piet = "0.6.0"
piet-common = "0.6.0"
kurbo = "0.9.0"

[features]
Text = []