[package]
name = "raycast-tests"
version = "0.10.10"
edition = "2021"
default-run = "run"

[dependencies]
pax-lang = { version = "0.11.2"}
pax-std = { version = "0.11.2"}
pax-compiler = { version = "0.11.2", optional = true}
pax-manifest = { version = "0.11.2"}
serde_json = {version = "1.0.95", optional = true}

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
parser = ["pax-std/parser", "pax-lang/parser", "dep:serde_json", "dep:pax-compiler"]
