[package]
name = "mouse-animation"
version = "0.14.1"
edition = "2021"
default-run = "run"

[dependencies]
<<<<<<< HEAD:examples/src/mouse-animation/Cargo.toml
pax-engine = { version = "0.14.3"}
pax-std = { version = "0.14.3"}
pax-compiler = { version = "0.14.3", optional = true }
pax-manifest = { version = "0.14.3", optional = true }
=======
pax-engine = { version = "0.13.21" }
pax-std = { version = "0.13.21" }
pax-compiler = { version = "0.13.21", optional = true }
pax-manifest = { version = "0.13.21", optional = true }
>>>>>>> 20fa6df6 (Release 0.13.21):examples/src/pax-intro/Cargo.toml
serde_json = {version = "1.0.95", optional = true}

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
parser = ["pax-std/parser", "pax-engine/parser", "dep:serde_json", "dep:pax-compiler", "dep:pax-manifest"]
