[package]
name = "pax-cartridge"
version = "0.5.7"
authors = ["Zack Brown <zack@pax.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://pax.dev/"
repository = "https://www.github.com/pax-lang/pax"
description = "Static program definition container for Pax programs, intended to be patched during compilation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piet-common = "0.6.0"
pax-core = {path = "../pax-core", version = "0.5.7"}
pax-runtime-api = {path = "../pax-runtime-api", version = "0.5.7"}
pax-properties-coproduct = {path = "../pax-example/.pax/properties-coproduct", version="0.5.7"}


pax-std-primitives = {path = "../pax-std/pax-std-primitives", version = "0.5.7"}

