#!/bin/bash

### Helper binary for pax libdev, allowing pax-cli-like ergonomics inside the pax-example directory
### For example, from @/pax root:
### `cd pax-example && ./pax run --target=macos`
### `cd pax-example && ./pax parse`
### `cd pax-example && ./pax libdev build-chassis`

pushd ../pax-cli
cargo run -- "$@" --path="../pax-example"
popd