#!/bin/bash

### Helper binary for pax libdev, allowing pax-cli-like ergonomics inside the pax-example directory
### For example, from @/pax root:
### `cd pax-example && ./pax run --target=macos`
### `cd pax-example && ./pax parse`
### `cd pax-example && ./pax libdev build-chassis`

pushd ../pax-cli > /dev/null

libdev_mode="--libdev"
if [ $1 = "clean" ]; then
    # The clean command does not expect the "--libdev" argument which we supply by default.
    libdev_mode=""
fi

cargo run -- "$@" --path="../pax-example" $libdev_mode
popd > /dev/null
