[package]
name = "starter-project"
version = "0.38.3"
edition = "2021"
default-run = "run"

[dependencies]
pax-kit = { version = "0.38.3", path="../../../pax-kit"}
fireworks = { version = "0.38.3", path="../fireworks" }
color-picker = { version = "0.38.3", path="../color-picker" }
breakout = { version = "0.38.3", path="../breakout" }
space-game = { version = "0.38.3", path="../space-game" }

[lib]
crate-type = ["cdylib", "rlib"]
name = "paxcartridge"

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
designtime = ["pax-kit/designtime"]
designer = ["designtime", "pax-kit/designer"]
web = ["pax-kit/web"]
webgl = ["pax-kit/webgl"]
macos = ["pax-kit/macos"]
ios = ["pax-kit/ios"]

[profile.dev]
opt-level = 0
debug = false

[profile.dev.package."*"]
opt-level = 2
debug = false

[profile.release]
opt-level = 3
lto = "thin"

