[package]
name = "starter-project"
version = "0.38.3"
edition = "2021"
default-run = "run"

[package.metadata.pax]
title = "Starter Project"
icon = "assets/app-icon.png"

[dependencies]
pax-kit = { version = "0.38.3", path="../../../pax-kit"}
fireworks = { version = "0.38.3", path="../fireworks" }
color-picker = { version = "0.38.3", path="../color-picker" }
breakout = { version = "0.38.3", path="../breakout" }
space-game = { version = "0.38.3", path="../space-game" }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "run"
path = "bin/run.rs"

[profile.release]
opt-level = 3
lto = "thin"
