#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
usage: scripts/clean-temp-files.sh [--dry-run]

Removes gitignored Pax build artifacts from the monorepo:
  - target/ directories
  - .pax/ directories generated by Pax build/dev flows

The script must be run from the Pax monorepo root. It skips any candidate
directory that is not ignored by git or that contains tracked files.

Options:
  -n, --dry-run   Print what would be removed without deleting anything.
  -h, --help      Show this help text.
USAGE
}

dry_run=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--dry-run)
      dry_run=true
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
  shift
done

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$repo_root" ]]; then
  echo "error: not inside a git repository" >&2
  exit 69
fi

repo_root="$(cd "$repo_root" && pwd -P)"
cwd="$(pwd -P)"

if [[ "$cwd" != "$repo_root" ]]; then
  echo "error: run this script from the Pax monorepo root" >&2
  echo "repo root: $repo_root" >&2
  echo "current:   $cwd" >&2
  exit 64
fi

if [[ ! -f Cargo.toml || ! -d pax-cli || ! -d examples/src ]]; then
  echo "error: current directory does not look like the Pax monorepo root" >&2
  exit 64
fi

paths=()

is_same_or_descendant() {
  local ancestor="${1%/}"
  local path="${2%/}"

  [[ "$path" == "$ancestor" || "$path" == "$ancestor"/* ]]
}

assert_safe_delete_path() {
  local path="$1"
  local base parent parent_abs

  case "$path" in
    ""|"."|".."|"/"|/*|../*|*/../*|*/..)
      echo "refusing unsafe delete path: $path" >&2
      exit 65
      ;;
  esac

  base="$(basename -- "$path")"
  if [[ "$base" != "target" && "$base" != ".pax" ]]; then
    echo "refusing unexpected temp directory name: $path" >&2
    exit 65
  fi

  parent="$(dirname -- "$path")"
  if [[ ! -d "$parent" ]]; then
    echo "refusing path with missing parent directory: $path" >&2
    exit 65
  fi

  parent_abs="$(cd "$parent" && pwd -P)"
  case "$parent_abs/" in
    "$repo_root"/*)
      ;;
    *)
      echo "refusing path outside repo root: $path" >&2
      exit 65
      ;;
  esac
}

disk_kib_for_paths() {
  local total=0
  local size

  while read -r size _; do
    if [[ "$size" =~ ^[0-9]+$ ]]; then
      ((total += size))
    fi
  done < <(du -sk -- "$@")

  printf '%s\n' "$total"
}

format_kib() {
  local kib="$1"

  awk -v kib="$kib" 'BEGIN {
    split("KiB MiB GiB TiB", units)
    value = kib
    unit = 1

    while (value >= 1024 && unit < 4) {
      value /= 1024
      unit++
    }

    if (unit == 1) {
      printf "%d %s", value, units[unit]
    } else {
      printf "%.1f %s", value, units[unit]
    }
  }'
}

add_path() {
  local path="$1"
  local existing
  local retained=()

  path="${path#./}"

  if [[ -z "$path" || ! -d "$path" ]]; then
    return
  fi

  assert_safe_delete_path "$path"

  if ! git check-ignore -q -- "$path"; then
    echo "skipping non-ignored directory: $path" >&2
    return
  fi

  if [[ -n "$(git ls-files -- "$path")" ]]; then
    echo "skipping directory with tracked files: $path" >&2
    return
  fi

  for existing in "${paths[@]}"; do
    if is_same_or_descendant "$existing" "$path"; then
      return
    fi
  done

  for existing in "${paths[@]}"; do
    if ! is_same_or_descendant "$path" "$existing"; then
      retained+=("$existing")
    fi
  done

  paths=("${retained[@]}" "$path")
}

while IFS= read -r -d '' path; do
  add_path "$path"
done < <(
  find . \
    \( -path './.git' -o -path './vendor' -o -path './node_modules' -o -path './.cargo' \) -prune \
    -o -type d -name target -prune -print0
)

while IFS= read -r -d '' path; do
  add_path "$path"
done < <(
  find . \
    \( -path './.git' -o -path './vendor' -o -path './node_modules' -o -path './.cargo' -o -type d -name target \) -prune \
    -o -type d -name .pax -prune -print0
)

if [[ "${#paths[@]}" -eq 0 ]]; then
  echo "No temp directories found."
  exit 0
fi

echo "Temp directories to remove:"
printf '  %s\n' "${paths[@]}"

disk_kib="$(disk_kib_for_paths "${paths[@]}")"
disk_human="$(format_kib "$disk_kib")"
echo "Estimated disk space to free: $disk_human ($disk_kib KiB)"

if [[ "$dry_run" == true ]]; then
  echo "Dry run only; no directories removed."
  exit 0
fi

for path in "${paths[@]}"; do
  assert_safe_delete_path "$path"
done

rm -rf -- "${paths[@]}"
echo "Removed ${#paths[@]} temp directories; freed approximately $disk_human."
