#!/bin/bash

### Helper script for pax libdev, allowing pax-cli-like ergonomics inside the pax-example directory

set -e
current_dir=$(pwd)
pushd ../../../pax-cli
cargo build
PAX_WORKSPACE_ROOT=.. ../target/debug/pax-cli "$@" --path="$current_dir" --libdev
popd
