[package]
name = "slot-particles"
version = "0.36.8"
edition = "2021"
default-run = "run"

[dependencies]
rand = { version = "0.8.5" }
getrandom = { version = "0.2.15", features = ["js"] }
pax-kit = { version = "0.36.8", path="../../../pax-kit" }
fireworks = {version = "0.36.3", path="../fireworks" }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "parser"
path = "src/lib.rs"
required-features = ["parser"]

[[bin]]
name = "run"
path = "bin/run.rs"

[features]
designer = ["pax-kit/designer", "fireworks/designer"]
parser = ["pax-kit/parser", "fireworks/parser"]
web = ["pax-kit/web"]
macos = ["pax-kit/macos"]
ios = ["pax-kit/ios"]

[profile.parser]
inherits = "dev"
opt-level = 0

[profile.parser.package."*"]
inherits = "dev"
opt-level = 0

[profile.dev]
opt-level = 0
debug = false

[profile.dev.package."*"]
opt-level = 2
debug = false