// Generated by pax-docs/scripts/generate_pax_highlight.py.
// Source grammar: pax-language/src/pax.pest sha256:a4d9ffbcce31182b
// Output: pax-docs/book/theme/highlight-pax.js
(function () {
    const PAX_GRAMMAR_TOKENS = {
        keywords: [
    "bind",
    "else",
    "for",
    "if",
    "in",
    "key",
    "self",
    "settings",
    "slot",
    "this",
    "timeline"
],
        booleanLiterals: [
    "false",
    "true"
],
        optionLiterals: [
    "None",
    "Option",
    "Some"
],
        colorConstants: [
    "AMBER",
    "BLACK",
    "BLUE",
    "CYAN",
    "EMERALD",
    "FUCHSIA",
    "GRAY",
    "GREEN",
    "INDIGO",
    "LIME",
    "NEUTRAL",
    "NONE",
    "ORANGE",
    "PINK",
    "PURPLE",
    "RED",
    "ROSE",
    "SKY",
    "SLATE",
    "STONE",
    "TEAL",
    "TRANSPARENT",
    "VIOLET",
    "WHITE",
    "YELLOW",
    "ZINC"
],
        colorFunctions: [
    "hsl",
    "hsla",
    "rgb",
    "rgba"
],
        units: [
    "%",
    "deg",
    "f",
    "ms",
    "px",
    "rad",
    "s"
]
    };

    const KEYWORDS = new Set(PAX_GRAMMAR_TOKENS.keywords);
    const LITERALS = new Set(
        PAX_GRAMMAR_TOKENS.booleanLiterals
            .concat(PAX_GRAMMAR_TOKENS.optionLiterals)
            .concat(PAX_GRAMMAR_TOKENS.colorConstants)
    );
    const COLOR_FUNCTIONS = new Set(PAX_GRAMMAR_TOKENS.colorFunctions);
    const UNITS = new Set(PAX_GRAMMAR_TOKENS.units.filter((unit) => /^[A-Za-z]+$/.test(unit)));
    const OPERATORS = ["==", "!=", ">=", "<=", "&&", "||", "%%", "??", "..", "::", "+", "-", "*", "/", "%", "^", "?", ":", "=", ">", "<", "!", ",", ".", "[", "]", "(", ")"];

    function escapeHtml(value) {
        return value
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/"/g, "&quot;")
            .replace(/'/g, "&#x27;");
    }

    function span(className, value) {
        return `<span class="hljs-${className}">${escapeHtml(value)}</span>`;
    }

    function isWhitespace(ch) {
        return ch === " " || ch === "\t" || ch === "\n" || ch === "\r";
    }

    function isIdentStart(ch) {
        return !!ch && /[A-Za-z_]/.test(ch);
    }

    function isIdentPart(ch) {
        return !!ch && /[A-Za-z0-9_-]/.test(ch);
    }

    function readIdentifier(source, index) {
        if (!isIdentStart(source[index])) {
            return null;
        }
        let end = index + 1;
        while (end < source.length && isIdentPart(source[end])) {
            end += 1;
        }
        return { text: source.slice(index, end), end };
    }

    function nextNonWhitespace(source, index) {
        let cursor = index;
        while (cursor < source.length && isWhitespace(source[cursor])) {
            cursor += 1;
        }
        return cursor;
    }

    function readString(source, index) {
        const quote = source[index];
        let cursor = index + 1;
        let escaped = false;
        while (cursor < source.length) {
            const ch = source[cursor];
            cursor += 1;
            if (escaped) {
                escaped = false;
            } else if (ch === "\\") {
                escaped = true;
            } else if (ch === quote) {
                break;
            }
        }
        return { html: span("string", source.slice(index, cursor)), index: cursor };
    }

    function readComment(source, index) {
        if (source.startsWith("//", index)) {
            let end = source.indexOf("\n", index + 2);
            if (end === -1) {
                end = source.length;
            } else {
                end += 1;
            }
            return { html: span("comment", source.slice(index, end)), index: end };
        }
        if (source.startsWith("/*", index)) {
            const close = source.indexOf("*/", index + 2);
            const end = close === -1 ? source.length : close + 2;
            return { html: span("comment", source.slice(index, end)), index: end };
        }
        if (source.startsWith("<!--", index)) {
            const close = source.indexOf("-->", index + 4);
            const end = close === -1 ? source.length : close + 3;
            return { html: span("comment", source.slice(index, end)), index: end };
        }
        return null;
    }

    function readNumber(source, index) {
        const match = source.slice(index).match(/^-?(?:(?:\d+(?:\.\d+)?)|(?:\.\d+))(?:%|px|deg|rad)?/);
        if (!match) {
            return null;
        }
        const before = index > 0 ? source[index - 1] : "";
        const after = source[index + match[0].length] || "";
        if ((/[A-Za-z0-9_]/.test(before) && source[index] !== "-") || /[A-Za-z0-9_]/.test(after)) {
            return null;
        }
        return { html: span("number", match[0]), index: index + match[0].length };
    }

    function readAtDirective(source, index) {
        const ident = readIdentifier(source, index + 1);
        if (!ident) {
            return null;
        }
        let html = span("meta", source.slice(index, ident.end));
        let cursor = ident.end;
        if (ident.text === "timeline") {
            const name = readIdentifier(source, nextNonWhitespace(source, cursor));
            if (name) {
                html += escapeHtml(source.slice(cursor, name.end).replace(name.text, ""));
                html += span("title", name.text);
                cursor = name.end;
            }
        }
        return { html, index: cursor };
    }

    function readSelector(source, index) {
        const prefix = source[index];
        if (prefix !== "#" && prefix !== ".") {
            return null;
        }
        const ident = readIdentifier(source, index + 1);
        if (!ident) {
            return null;
        }
        return {
            html: span(prefix === "#" ? "selector-id" : "selector-class", source.slice(index, ident.end)),
            index: ident.end
        };
    }

    function readOperator(source, index, allowed) {
        const operators = allowed || OPERATORS;
        for (const op of operators) {
            if (source.startsWith(op, index)) {
                return { html: span("operator", op), index: index + op.length };
            }
        }
        return null;
    }

    function classifyIdentifier(source, index, context) {
        const first = readIdentifier(source, index);
        if (!first) {
            return null;
        }

        let cursor = first.end;
        const pathParts = [first.text];
        while (source.startsWith("::", cursor)) {
            const next = readIdentifier(source, cursor + 2);
            if (!next) {
                break;
            }
            pathParts.push(next.text);
            cursor = next.end;
        }
        if (pathParts.length > 1) {
            let html = "";
            pathParts.forEach((part, partIndex) => {
                if (partIndex > 0) {
                    html += span("operator", "::");
                }
                html += span("symbol", part);
            });
            return { html, index: cursor };
        }

        const name = first.text;
        const lookahead = nextNonWhitespace(source, first.end);
        const ch = source[lookahead];
        const nextTwo = source.slice(lookahead, lookahead + 2);
        if (context && context.tag && (ch === "=" || ch === ":") && nextTwo !== "==" && nextTwo !== "::") {
            return { html: span("attr", name), index: first.end };
        }
        if ((!context || !context.expression) && (ch === "=" || ch === ":") && nextTwo !== "==" && nextTwo !== "::") {
            return { html: span("attr", name), index: first.end };
        }
        if (COLOR_FUNCTIONS.has(name) && ch === "(") {
            return { html: span("built_in", name), index: first.end };
        }
        if (KEYWORDS.has(name)) {
            return { html: span("keyword", name), index: first.end };
        }
        if (LITERALS.has(name)) {
            return { html: span("literal", name), index: first.end };
        }
        if (UNITS.has(name)) {
            return { html: span("number", name), index: first.end };
        }
        if (ch === "(") {
            return { html: span("title", name), index: first.end };
        }
        if (/^[A-Z]/.test(name) && /[a-z]/.test(name)) {
            return { html: span(ch === "{" ? "type" : "symbol", name), index: first.end };
        }
        return { html: span("variable", name), index: first.end };
    }

    function scanBracedExpression(source, index) {
        let html = `<span class="hljs-template-variable">${escapeHtml(source[index])}`;
        let cursor = index + 1;
        while (cursor < source.length) {
            const ch = source[cursor];
            if (ch === "}") {
                html += escapeHtml(ch) + "</span>";
                return { html, index: cursor + 1 };
            }
            if (ch === "{") {
                const nested = scanBracedExpression(source, cursor);
                html += nested.html;
                cursor = nested.index;
                continue;
            }
            const token = scanToken(source, cursor, { expression: true });
            html += token.html;
            cursor = token.index;
        }
        html += "</span>";
        return { html, index: cursor };
    }

    function scanTag(source, index) {
        let cursor = index;
        let html = "";
        if (source.startsWith("</", cursor)) {
            html += span("tag", "</");
            cursor += 2;
        } else {
            html += span("tag", "<");
            cursor += 1;
        }

        const name = readIdentifier(source, cursor);
        if (name) {
            html += span("name", name.text);
            cursor = name.end;
        }

        while (cursor < source.length) {
            if (source.startsWith("/>", cursor)) {
                html += span("tag", "/>");
                return { html, index: cursor + 2 };
            }
            if (source[cursor] === ">") {
                html += span("tag", ">");
                return { html, index: cursor + 1 };
            }
            if (source[cursor] === "{") {
                const expr = scanBracedExpression(source, cursor);
                html += expr.html;
                cursor = expr.index;
                continue;
            }
            if (source[cursor] === "@") {
                const directive = readAtDirective(source, cursor);
                if (directive) {
                    html += directive.html;
                    cursor = directive.index;
                    continue;
                }
            }
            const token = scanToken(source, cursor, { tag: true });
            html += token.html;
            cursor = token.index;
        }
        return { html, index: cursor };
    }

    function scanToken(source, index, context) {
        const ch = source[index];
        const comment = readComment(source, index);
        if (comment) {
            return comment;
        }
        if (ch === '"' || ch === "'" || ch === "`") {
            return readString(source, index);
        }
        if (isWhitespace(ch)) {
            return { html: escapeHtml(ch), index: index + 1 };
        }
        if (ch === "@") {
            const directive = readAtDirective(source, index);
            if (directive) {
                return directive;
            }
        }
        if ((ch === "#" || ch === ".") && !(context && context.expression)) {
            const selector = readSelector(source, index);
            if (selector) {
                return selector;
            }
        }
        const number = readNumber(source, index);
        if (number) {
            return number;
        }
        if (isIdentStart(ch)) {
            const ident = classifyIdentifier(source, index, context || {});
            if (ident) {
                return ident;
            }
        }
        const operator = readOperator(source, index, context && context.tag ? ["="] : undefined);
        if (operator) {
            return operator;
        }
        return { html: escapeHtml(ch), index: index + 1 };
    }

    function highlightPax(source) {
        let html = "";
        let index = 0;
        while (index < source.length) {
            if (source[index] === "<" && /<\/?[A-Z]/.test(source.slice(index, index + 3))) {
                const tag = scanTag(source, index);
                html += tag.html;
                index = tag.index;
                continue;
            }
            const token = scanToken(source, index, {});
            html += token.html;
            index = token.index;
        }
        return html;
    }

    function isPaxCode(code) {
        return code && (
            code.classList.contains("language-pax") ||
            code.classList.contains("language-paxel") ||
            code.classList.contains("lang-pax") ||
            code.classList.contains("lang-paxel")
        );
    }

    function resetCode(code) {
        const source = code.textContent;
        code.textContent = source;
        code.classList.remove("no-highlight");
        code.removeAttribute("data-highlighted");
        delete code.result;
        delete code.second_best;
        return source;
    }

    function highlightCode(code) {
        if (!code) {
            return;
        }
        const source = resetCode(code);
        if (isPaxCode(code)) {
            code.innerHTML = highlightPax(source);
            code.classList.add("hljs");
            return;
        }
        if (window.hljs && typeof window.hljs.highlightElement === "function") {
            window.hljs.highlightElement(code);
        } else if (window.hljs && typeof window.hljs.highlightBlock === "function") {
            window.hljs.highlightBlock(code);
        }
        code.classList.add("hljs");
    }

    function highlightPaxBlocks(root) {
        (root || document)
            .querySelectorAll("code.language-pax, code.language-paxel, code.lang-pax, code.lang-paxel")
            .forEach(highlightCode);
    }

    window.PaxHighlight = {
        highlightCode,
        highlightPax,
        highlightPaxBlocks
    };

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", () => highlightPaxBlocks(document));
    } else {
        highlightPaxBlocks(document);
    }
})();
