"""Local integration-path tests; no Zola download, server, or AWS calls."""
import importlib.util
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch


SPEC = importlib.util.spec_from_file_location("pax_blog", Path(__file__).with_name("blog.py"))
blog = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(blog)


class WebsiteStagingTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="pax-blog-staging-test-")
        self.addCleanup(self.temporary.cleanup)
        self.repo = Path(self.temporary.name)
        self.root = self.repo / "pax-blog"
        theme = self.root / "themes/tabi"
        theme.mkdir(parents=True)
        (theme / "theme.toml").touch()
        self.staged = self.repo / "pax-website/public/blog"
        self.root_patch = patch.object(blog, "ROOT", self.root)
        self.root_patch.start()
        self.addCleanup(self.root_patch.stop)

    def invoke(self, *arguments):
        with patch("sys.argv", ["blog.py", *arguments]):
            blog.main()

    def test_stage_and_unstage_use_the_root_sibling_without_touching_old_location(self):
        old_location = self.repo / "examples/src/pax-website/public/blog"
        old_location.mkdir(parents=True)
        sentinel = old_location / "keep.txt"
        sentinel.write_text("unrelated content")

        def build(command, **kwargs):
            self.assertEqual(command[:3], ["zola", "--root", str(self.root)])
            self.assertIn("--drafts", command)
            self.assertIn("http://127.0.0.1:8123/blog", command)
            output = Path(command[command.index("--output-dir") + 1])
            self.assertEqual(output, self.staged)
            output.mkdir(parents=True)
            (output / "index.html").write_text("draft preview")

        with patch.object(blog, "zola", return_value="zola"), patch.object(
            blog.subprocess, "run", side_effect=build
        ) as run:
            self.invoke("stage", "--port", "8123")
            self.assertEqual(run.call_count, 1)
        self.assertTrue((self.staged / ".pax-blog-preview").is_file())
        self.invoke("unstage")
        self.assertFalse(self.staged.exists())
        self.assertEqual(sentinel.read_text(), "unrelated content")

    def test_unstage_refuses_unmarked_content_in_the_new_location(self):
        self.staged.mkdir(parents=True)
        sentinel = self.staged / "index.html"
        sentinel.write_text("not generated by this helper")
        with self.assertRaisesRegex(SystemExit, "unmarked directory"):
            self.invoke("unstage")
        self.assertTrue(sentinel.is_file())

    def test_production_build_still_excludes_drafts_and_staging(self):
        with patch.object(blog, "zola", return_value="zola"), patch.object(
            blog.subprocess, "run"
        ) as run:
            self.invoke("build")
        run.assert_called_once_with(["zola", "--root", str(self.root), "build"], check=True)
        self.assertFalse(self.staged.exists())


if __name__ == "__main__":
    unittest.main()
