[package]
name = "generated_project"
version = "0.13.19"
edition = "2021"
default-run = "run"

[dependencies]
pax-kit = { version = "0.35.0", path="../../pax-kit" }
rand = { version = "0.8.5" }
getrandom = { version = "0.2.15", features = ["js"] }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "run"
path = "bin/run.rs"
