name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always
 
jobs:
  build:
    runs-on: mars
    steps:
    - uses: actions/checkout@v3

    - name: Cache installed tools
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin
          ~/.local/share/pax-cli
        key: ${{ runner.os }}-tools-${{ hashFiles('**/Cargo.lock') }}

    # Install dependencies
    - name: Install dependencies
      run: |
        if ! command -v wasm-pack &> /dev/null; then
          sudo apt update && sudo apt install -y libgtk-4-dev
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        fi
        if ! command -v pax-cli &> /dev/null; then
          cargo install pax-cli
        fi
        

    - name: Build Starter Project
      run: pushd examples/src/starter-project && pax-cli build --release && popd

    # - name: Run tests
    #   run: cargo test --verbose --workspace --exclude pax-chassis-macos --exclude pax-chassis-common --exclude pax-chassis-ios

    # - name: Check formatting
    #   run: cargo fmt -- --check

    # - name: Check for linting errors
    #   run: |
    #     rustup component add clippy
    #     cargo clippy -- -D warnings